from dotenv import load_dotenv
import os

load_dotenv()

MONGO_URI = os.getenv('MONGO_URI')
SECRET_KEY = os.getenv('SECRET_KEY')

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')

CLOUDINARY_CLOUD_NAME2 = os.getenv('CLOUDINARY_CLOUD_NAME2')
CLOUDINARY_API_KEY2 = os.getenv('CLOUDINARY_API_KEY2')
CLOUDINARY_API_SECRET2 = os.getenv('CLOUDINARY_API_SECRET2')

FASHN_API_KEY = os.getenv('FASHN_API_KEY')